rabbitmq:
  url: "amqp://guest:guest@10.50.99.128:5672/"
  exchange: "its.events"
  exchangeType: "direct"
  routingKey: "camera.event"
  retry: 5
  retryDelay: 2s

dahua:
  username: "admin"
  password: "SsgCT7LB@123"
  laneMap:        
    lane-01: "172.19.11.173"
    lane-02: "192.168.1.102"
    lane-03: "192.168.1.103"

server:
  port: "8080"        
  read_timeout: 10s
  write_timeout: 10s
  request_id_header: "X-Request-ID"

logging:
  level: "info" 
  format: "json"
