# Dockerfile.gateway
FROM golang:1.24.5-alpine AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN go build -o its-gateway ./cmd/gateway

# Final minimal image
FROM alpine:latest

WORKDIR /app

COPY --from=builder /app/its-gateway .
COPY config.yml .

EXPOSE 8080

CMD ["./its-gateway"]
