FROM golang:1.24.5-alpine AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN go build -o its-consumer ./cmd/consumer

# Final minimal image
FROM alpine:latest

WORKDIR /app

COPY --from=builder /app/its-consumer .
COPY config.yml .

CMD ["./its-consumer"]
